[language]
name = "name of the language"
compiler = "compiler executable"
extensions = ["ext", "exmpl", "exam"]
# standard = "-std=c++20"
warnings = ["-Wsome", "-Wsomemore"]
output = "-o" # not entirely sure about this one
optimization_levels = ["-Optimization1", "-Optimization5"]
