[language]
name = ""
output = "-o"
optimization_levels = ["-g", "-O0", "-O1", "-O2", "-O3"] # `-Og` ?

[workspace]
dir = "cpp"
src = "main.cpp"
template = "main.cpp"

[cmd]
build = "g++ -std=c++20 -Wall -Wextra -Wpedantic -O3 ./src/SRC -o ./bin/OUT"
run = "BUILD"
